"%programfiles%\Microsoft VS Code\Code.exe" --install-extension yo1dog.cursor-align
"%programfiles%\Microsoft VS Code\Code.exe" --install-extension Tyriar.sort-lines
"%programfiles%\Microsoft VS Code\Code.exe" --install-extension twxs.cmake
"%programfiles%\Microsoft VS Code\Code.exe" --install-extension svelte.svelte-vscode
"%programfiles%\Microsoft VS Code\Code.exe" --install-extension qcz.text-power-tools
"%programfiles%\Microsoft VS Code\Code.exe" --install-extension ms-vscode.sublime-keybindings
"%programfiles%\Microsoft VS Code\Code.exe" --install-extension ms-vscode.remote-server
"%programfiles%\Microsoft VS Code\Code.exe" --install-extension ms-vscode.remote-explorer
"%programfiles%\Microsoft VS Code\Code.exe" --install-extension ms-vscode.powershell
"%programfiles%\Microsoft VS Code\Code.exe" --install-extension ms-vscode.cpptools-extension-pack
"%programfiles%\Microsoft VS Code\Code.exe" --install-extension ms-vscode.cpptools
"%programfiles%\Microsoft VS Code\Code.exe" --install-extension ms-vscode.cmake-tools
"%programfiles%\Microsoft VS Code\Code.exe" --install-extension ms-vscode-remote.vscode-remote-extensionpack
"%programfiles%\Microsoft VS Code\Code.exe" --install-extension ms-vscode-remote.remote-wsl
"%programfiles%\Microsoft VS Code\Code.exe" --install-extension ms-vscode-remote.remote-ssh-edit
"%programfiles%\Microsoft VS Code\Code.exe" --install-extension ms-vscode-remote.remote-ssh
"%programfiles%\Microsoft VS Code\Code.exe" --install-extension ms-vscode-remote.remote-containers
"%programfiles%\Microsoft VS Code\Code.exe" --install-extension ms-toolsai.vscode-jupyter-slideshow
"%programfiles%\Microsoft VS Code\Code.exe" --install-extension ms-toolsai.vscode-jupyter-cell-tags
"%programfiles%\Microsoft VS Code\Code.exe" --install-extension ms-toolsai.jupyter-renderers
"%programfiles%\Microsoft VS Code\Code.exe" --install-extension ms-toolsai.jupyter-keymap
"%programfiles%\Microsoft VS Code\Code.exe" --install-extension ms-toolsai.jupyter
"%programfiles%\Microsoft VS Code\Code.exe" --install-extension ms-toolsai.datawrangler
"%programfiles%\Microsoft VS Code\Code.exe" --install-extension ms-python.vscode-pylance
"%programfiles%\Microsoft VS Code\Code.exe" --install-extension ms-python.python
"%programfiles%\Microsoft VS Code\Code.exe" --install-extension ms-python.debugpy
"%programfiles%\Microsoft VS Code\Code.exe" --install-extension ms-dotnettools.vscode-dotnet-runtime
"%programfiles%\Microsoft VS Code\Code.exe" --install-extension ms-dotnettools.csharp
"%programfiles%\Microsoft VS Code\Code.exe" --install-extension ms-dotnettools.csdevkit
"%programfiles%\Microsoft VS Code\Code.exe" --install-extension ms-azuretools.vscode-docker
"%programfiles%\Microsoft VS Code\Code.exe" --install-extension mechatroner.rainbow-csv
"%programfiles%\Microsoft VS Code\Code.exe" --install-extension github.vscode-github-actions
"%programfiles%\Microsoft VS Code\Code.exe" --install-extension GitHub.copilot-chat
"%programfiles%\Microsoft VS Code\Code.exe" --install-extension GitHub.copilot
"%programfiles%\Microsoft VS Code\Code.exe" --install-extension fabiospampinato.vscode-diff
"%programfiles%\Microsoft VS Code\Code.exe" --install-extension earshinov.permute-lines
"%programfiles%\Microsoft VS Code\Code.exe" --install-extension eamodio.gitlens
"%programfiles%\Microsoft VS Code\Code.exe" --install-extension acarreiro.calculate