code --install-extension yo1dog.cursor-align
code --install-extension Tyriar.sort-lines
code --install-extension twxs.cmake
code --install-extension svelte.svelte-vscode
code --install-extension qcz.text-power-tools
code --install-extension ms-vscode.sublime-keybindings
code --install-extension ms-vscode.remote-server
code --install-extension ms-vscode.remote-explorer
code --install-extension ms-vscode.powershell
code --install-extension ms-vscode.cpptools-extension-pack
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.cmake-tools
code --install-extension ms-vscode-remote.vscode-remote-extensionpack
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.datawrangler
code --install-extension ms-python.vscode-pylance
code --install-extension ms-python.python
code --install-extension ms-python.debugpy
code --install-extension ms-dotnettools.vscode-dotnet-runtime
code --install-extension ms-dotnettools.csharp
code --install-extension ms-dotnettools.csdevkit
code --install-extension ms-azuretools.vscode-docker
code --install-extension mechatroner.rainbow-csv
code --install-extension github.vscode-github-actions
code --install-extension GitHub.copilot-chat
code --install-extension GitHub.copilot
code --install-extension fabiospampinato.vscode-diff
code --install-extension earshinov.permute-lines
code --install-extension eamodio.gitlens
code --install-extension acarreiro.calculate