cd "%programfiles%\Microsoft VS Code\bin"
start /WAIT cmd /C .\code --install-extension yo1dog.cursor-align
start /WAIT cmd /C .\code --install-extension Tyriar.sort-lines
start /WAIT cmd /C .\code --install-extension twxs.cmake
start /WAIT cmd /C .\code --install-extension svelte.svelte-vscode
start /WAIT cmd /C .\code --install-extension qcz.text-power-tools
start /WAIT cmd /C .\code --install-extension ms-vscode.sublime-keybindings
start /WAIT cmd /C .\code --install-extension ms-vscode.remote-server
start /WAIT cmd /C .\code --install-extension ms-vscode.remote-explorer
start /WAIT cmd /C .\code --install-extension ms-vscode.powershell
start /WAIT cmd /C .\code --install-extension ms-vscode.cpptools-extension-pack
start /WAIT cmd /C .\code --install-extension ms-vscode.cpptools
start /WAIT cmd /C .\code --install-extension ms-vscode.cmake-tools
start /WAIT cmd /C .\code --install-extension ms-vscode-remote.vscode-remote-extensionpack
start /WAIT cmd /C .\code --install-extension ms-vscode-remote.remote-wsl
start /WAIT cmd /C .\code --install-extension ms-vscode-remote.remote-ssh-edit
start /WAIT cmd /C .\code --install-extension ms-vscode-remote.remote-ssh
start /WAIT cmd /C .\code --install-extension ms-vscode-remote.remote-containers
start /WAIT cmd /C .\code --install-extension ms-toolsai.vscode-jupyter-slideshow
start /WAIT cmd /C .\code --install-extension ms-toolsai.vscode-jupyter-cell-tags
start /WAIT cmd /C .\code --install-extension ms-toolsai.jupyter-renderers
start /WAIT cmd /C .\code --install-extension ms-toolsai.jupyter-keymap
start /WAIT cmd /C .\code --install-extension ms-toolsai.jupyter
start /WAIT cmd /C .\code --install-extension ms-toolsai.datawrangler
start /WAIT cmd /C .\code --install-extension ms-python.vscode-pylance
start /WAIT cmd /C .\code --install-extension ms-python.python
start /WAIT cmd /C .\code --install-extension ms-python.debugpy
start /WAIT cmd /C .\code --install-extension ms-dotnettools.vscode-dotnet-runtime
start /WAIT cmd /C .\code --install-extension ms-dotnettools.csharp
start /WAIT cmd /C .\code --install-extension ms-dotnettools.csdevkit
start /WAIT cmd /C .\code --install-extension ms-azuretools.vscode-docker
start /WAIT cmd /C .\code --install-extension mechatroner.rainbow-csv
start /WAIT cmd /C .\code --install-extension github.vscode-github-actions
start /WAIT cmd /C .\code --install-extension GitHub.copilot-chat
start /WAIT cmd /C .\code --install-extension GitHub.copilot
start /WAIT cmd /C .\code --install-extension fabiospampinato.vscode-diff
start /WAIT cmd /C .\code --install-extension earshinov.permute-lines
start /WAIT cmd /C .\code --install-extension eamodio.gitlens
start /WAIT cmd /C .\code --install-extension acarreiro.calculate